language: ruby
rvm:
- 2.2.3
before_script:
- chmod +x "./script/cibuild"
script: "./script/cibuild"
install: bundle install

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: gF5s9F/q66uBdV/QUjBpXG+EG6Q/uaiY4M5wsOc65GSpx+M1a2mLzdwKcrGwkiIcmAf9K1KWPyVzovp1anmZSd6CxQzfeSNe42yfliqbuV/e+JDc7dGzCun454m3jeBW1oQ24NxRBf5ZvON+mNgyM1HA6ILh2aMmAb8ZQ+GIzVZR3qQXif/3sP0GmBnTdsg/V/v1AwADSYcVfV2qzQdYVV7GXaeNVQ5FxUfa1ycj0zy/Xl03L3eRJohCybTs1wNoB78QzKSK13jbZuL/NqRWbobYuFf7XF3H2jmmOJNSYQooyKYRlpm158MFeLNxq0yBIpzn2LNaVZksuhU12qJxV9mxg5TyGcM1rKAK2xcJCwhBTQFzFP7ZdzaHAF7sAYjZ340KPkKvB1qC6C9bcvQclYncBscc3jXvijXM4Qzm2R+8Qw1GJhcpmaCdhbT/eZaSc5ZfW1Z9M566efFfsvhNC0qISKAuwOBjGn3cOk4Tvu3HSzAG3uTG4Uo5cI3MsoyKMyuASmoB/0AxgJgtxZrbJxFRgSm8wQ6OIhOo6v+Zy6DPXUvlNIAJlK2sVmKhndbHYug3isb3gpdUbxs5AvC7Zm4TAqLP9DhEfh773blPbfvpaRJfs2zE8rzJWwOfXd/K8NCK5Kig8C22oTCIug/YDewL3O3hmc++iJVoCrrOQMc=
  - secure: BmWBtl8y0thfZ7HNcPqKW8TT8BTyG5qzZhDBGAJS9vVsELRzwxGyelYlmXVNOxT9On+dPExQEB/ONlvJPgLD3bWALpDQK66J1w8E4gFbXiZbId41PeJd7YLvkYoGz+Q3+IGxu+TNHHVPR4GrI+vtCAQ5u/YgfnctaDM0Fjjs76HgvSzAN6rGOvkxHvFhpiBIvUBi25V6Oier4kz0i8+5D4QlhvNSMq3qyrqm11r1Q9gAaEeaCEUfjZ7IHdwrOlK0i8d4+tz0jW6GJHdjX087rHxuuTD5uxxWlqKC3zVHDEDosx6tJ+fOAWYuxEboa8D4iOSJQzHvqh2HaRRqzJIrnEcLkc6YFoZUx6zX9zMf0bSD5ykhTFJloogj6RiRM4XiUm6wv0z5H7avSpcS+4SCFi2mngI/Mtb1OI3VrpnB0xJj5rwqJay3aSwlKqHyEI2W0pnHa5u9Z4RxlBCvxAS59BcWKcM5Z59nis8nv8jQUr5E0Vkqvzb49ApY85cvNqbwsxiyk/AbIemSfTSpDIGyjkgg6qAkpMNQBbbcUqlidEXp7Rm/3tsnRwN4EIpDatDFaJ4F8KNhQBtsiiaD8B1C1BRJsAVOKdeSsIenCAs+/addDzaJHCyD9J+HCHt/pq75v6eIun6UUES4P77kpa6sPhplV3tSizx38TlOt3cnY3g=
