# Site settings
title: Refugee Friendsgiving
email: admin@unrefugees.org
description: Refugee Friendsgiving
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://refugeefriendsgiving.co" # the base hostname & protocol for your site
twitter_username: unrefugeeagency


permalink: pretty

sass:
  sass_dir: ./_sass

# Build settings
markdown: kramdown

exclude: [vendor, 'Gemfile', 'Gemfile.lock', 'Readme.md']

assets:
  js_compressor: uglifier
  css_compressor: sass
