# Site settings
title: Friendsgiving
email: admin@unrefugees.org
description: Friendsgiving
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

permalink: pretty

sass:
  sass_dir: ./_sass

# Build settings
markdown: kramdown

exclude: [vendor, 'Gemfile', 'Gemfile.lock', 'Readme.md']
